plugins {
    id "com.android.application"
}

android {
    namespace "com.example.lightroomclone"
    compileSdk 33
    buildToolsVersion "33.0.2"

    defaultConfig {
        applicationId "com.example.lightroomclone"
        minSdk 26
        targetSdk 33
        versionCode 3
        versionName "1.2"
    }

    buildTypes {
        beta {
            initWith debug
            matchingFallbacks = ["debug"]
            debuggable false
            versionNameSuffix "-beta"
        }
    }
}
