plugins {
    id "com.android.application"
}

android {
    namespace "com.example.lightroomclone"
    compileSdk 33
    buildToolsVersion "33.0.2"

    defaultConfig {
        applicationId "com.zhouhaoran.mylight"
        minSdk 26
        targetSdk 33
        versionCode 12
        versionName "2.1"
    }

    signingConfigs {
        release {
            def props = new Properties()
            def propsFile = rootProject.file("release-signing.properties")
            if (propsFile.exists()) {
                props.load(new FileInputStream(propsFile))
                storeFile file(props["storeFile"])
                storePassword props["storePassword"]
                keyAlias props["keyAlias"]
                keyPassword props["keyPassword"]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        beta {
            initWith debug
            matchingFallbacks = ["debug"]
            debuggable false
            versionNameSuffix "-beta"
        }
    }
}
